<x-app-layout>
    <x-slot name="header"><x-ui.page-header title="Batch Detail" subtitle="Batch-level stock for the selected item and warehouse." /></x-slot>
    @php($qty = fn ($value) => number_format((float) $value, 2)) @php($date = fn ($value) => $value ? \Illuminate\Support\Carbon::parse($value)->format('d M Y') : '-') @php($uom = $record->baseUom?->code ?: $record->uom?->code ?: $record->item?->baseUnit?->code ?: '-')
    <div class="mx-auto max-w-screen-xl"><div class="mb-2 flex items-center justify-between rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm"><span><b>{{ $record->item?->sku }} - {{ $record->item?->name }}</b> · {{ $record->warehouse?->name }}</span><span>Warehouse {{ $qty($onHand) }} {{ $uom }} · Batch {{ $qty($batchTotal) }} · <b class="{{ abs($reconciliationDifference) <= 0.000001 ? 'text-emerald-700' : 'text-red-700' }}">{{ abs($reconciliationDifference) <= 0.000001 ? 'MATCHED' : 'MISMATCH '.$qty($reconciliationDifference) }}</b></span></div>
    @if(! $record->item?->is_batch_tracked)<div class="rounded-lg border border-slate-200 bg-white p-4 text-sm text-slate-600">This item is not batch tracked.</div>@else
    <x-ui.data-table class="rounded-lg shadow-none"><x-slot:head><tr><th class="px-3 py-2 text-left text-[11px] font-black uppercase text-slate-500">Batch No</th><th class="px-3 py-2 text-left text-[11px] font-black uppercase text-slate-500">Expiry Date</th><th class="px-3 py-2 text-right text-[11px] font-black uppercase text-slate-500">Qty On Hand</th><th class="px-3 py-2 text-left text-[11px] font-black uppercase text-slate-500">UOM</th><th class="px-3 py-2 text-left text-[11px] font-black uppercase text-slate-500">Expiry Status</th><th class="px-3 py-2"></th></tr></x-slot:head>
    @forelse($batchBalances as $batch) @php($status = $statusForBatch($batch->expiry_date))<tr class="text-xs"><td class="px-3 py-2 font-bold">{{ $batch->batch_no }}</td><td class="px-3 py-2">{{ $date($batch->expiry_date) }}</td><td class="px-3 py-2 text-right font-bold">{{ $qty($batch->qty_on_hand) }}</td><td class="px-3 py-2">{{ $uom }}</td><td class="px-3 py-2"><span class="inline-flex rounded-full px-2 py-0.5 font-bold ring-1 {{ $status[1] }}">{{ $status[0] }}</span></td><td class="px-3 py-2 text-right"><a class="font-bold text-emerald-700" href="{{ route('item-ledger.index', ['item_id'=>$record->item_id,'warehouse_id'=>$record->warehouse_id,'company_id'=>$record->company_id,'branch_id'=>$record->branch_id,'batch_no'=>$batch->batch_no]) }}">Ledger</a></td></tr>@empty <x-ui.empty-state colspan="6" message="No non-zero batch balances found." /> @endforelse
    </x-ui.data-table>@endif <a href="{{ route('stock-balances.index') }}" class="mt-3 inline-flex h-9 items-center rounded-lg border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700">Back</a></div>
</x-app-layout>
