@php
    $editing = $formula->exists;
    $selectedFinishedId = old('finished_item_id', $formula->finished_item_id);
    $selectedFinished = $items->firstWhere('id', (int) $selectedFinishedId);
    $rows = collect($materials)->map(function ($material) use ($items) {
        $item = $items->firstWhere('id', (int) ($material['item_id'] ?? 0));
        return ['item_id' => $material['item_id'] ?? '', 'item_text' => $item ? trim($item->sku.' - '.$item->name) : '', 'quantity' => $material['quantity'] ?? '', 'uom_id' => $material['uom_id'] ?? '', 'uom_code' => $item?->baseUnit?->code ?? '', 'quantity_type' => $material['quantity_type'] ?? 'proportional', 'source_warehouse_id' => $material['source_warehouse_id'] ?? '', 'notes' => $material['notes'] ?? ''];
    })->values();
    $warehouseLabel = fn ($warehouse) => trim($warehouse->code.' - '.$warehouse->name.' · '.($warehouse->branch?->name ?? 'No branch'));
@endphp

<x-app-layout>
    <x-slot name="header"><x-ui.page-header :title="$editing ? 'Edit Production Formula' : 'New Production Formula'" subtitle="One main output with base-UOM material inputs." /></x-slot>

    <form class="enterprise-form mx-auto max-w-screen-xl space-y-3" method="POST" action="{{ $editing ? route('production-formulas.update', $formula) : route('production-formulas.store') }}" x-data="formulaForm(@js($rows), @js(route('production-formulas.items')))" @linvy-finished-selected.window="selectFinished($event.detail)">
        @csrf
        @if ($editing) @method('PUT') @endif

        @if ($errors->any())
            <div class="status-danger rounded-lg px-4 py-3 text-sm"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
        @endif

        <x-form.section title="Formula Information">
            <x-form.grid>
                <x-form.select name="company_id" label="Company" required><option value="">Select company</option>@foreach ($companies as $id => $name)<option value="{{ $id }}" @selected((string) old('company_id', $formula->company_id ?: $defaultCompanyId) === (string) $id)>{{ $name }}</option>@endforeach</x-form.select>
                <x-form.select name="branch_id" label="Branch applicability"><option value="">Company-wide / All Branches</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" data-company="{{ $branch->company_id }}" @selected((string) old('branch_id', $formula->branch_id ?: $defaultBranchId) === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</x-form.select>
                <x-form.select name="production_type" label="Production type" required x-model="productionType" @change="onTypeChanged()">@foreach (\App\Models\ProductionBom::TYPES as $type)<option value="{{ $type }}" @selected(old('production_type', $formula->production_type ?: 'STANDARD') === $type)>{{ $type }}</option>@endforeach</x-form.select>
                <x-form.input name="name" label="Formula name" :value="old('name', $formula->name)" required x-model="formulaName" @input="nameTouched=true" />
                <div><span class="enterprise-form-label">Formula number</span><div class="enterprise-readonly">{{ $editing ? $formula->number : 'Auto-generated on save' }}</div></div>
                <div><span class="enterprise-form-label">Version</span><div class="enterprise-readonly">{{ $editing ? 'Version '.$formula->version : 'Assigned automatically on save' }}</div></div>
                <x-form.input name="effective_from" type="date" label="Effective from" :value="old('effective_from', $formula->effective_from?->format('Y-m-d') ?? now()->format('Y-m-d'))" />
                <x-form.input name="effective_to" type="date" label="Effective to" :value="old('effective_to', $formula->effective_to?->format('Y-m-d'))" />
            </x-form.grid>
            <x-form.textarea name="notes" label="Notes" :value="old('notes', $formula->notes)" />
        </x-form.section>

        <x-form.section title="Main Output"><x-form.grid>
            <div><label class="enterprise-form-label">Finished item</label><x-searchable-select name="finished_item_id" :url="route('production-formulas.items', ['intent' => 'output'])" placeholder="Search finished item by SKU or name..." :selected-id="$selectedFinishedId" :selected-text="$selectedFinished ? trim($selectedFinished->sku.' - '.$selectedFinished->name) : ''" :extra-params="['production_type' => '[name=production_type]']" on-select="window.dispatchEvent(new CustomEvent('linvy-finished-selected',{detail:option}))" required /></div>
            <x-form.input name="base_output_quantity" label="Base output quantity" :value="old('base_output_quantity', $formula->base_output_quantity ?: 1)" required step="0.000001" min="0.000001" x-model="baseOutput" @input="previewTouched || (preview=baseOutput)" />
            <div><label class="enterprise-form-label">Output UOM</label><input type="hidden" name="output_uom_id" x-model="outputUom"><div class="enterprise-readonly" x-text="outputCode || 'Select finished item'"></div></div>
            <x-form.select name="default_destination_warehouse_id" label="Default destination" data-destination><option value="">Select during execution</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" data-company="{{ $warehouse->company_id ?: $warehouse->branch?->company_id }}" data-branch="{{ $warehouse->branch_id }}" data-type="{{ $warehouse->warehouseType?->code }}" @selected((string) old('default_destination_warehouse_id', $formula->default_destination_warehouse_id) === (string) $warehouse->id)>{{ $warehouseLabel($warehouse) }}</option>@endforeach</x-form.select>
            <x-form.select name="default_source_warehouse_id" label="Default source" data-source x-model="defaultSourceWarehouseId"><option value="">Select during execution</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" data-company="{{ $warehouse->company_id ?: $warehouse->branch?->company_id }}" data-branch="{{ $warehouse->branch_id }}" data-type="{{ $warehouse->warehouseType?->code }}" @selected((string) old('default_source_warehouse_id', $formula->default_source_warehouse_id) === (string) $warehouse->id)>{{ $warehouseLabel($warehouse) }}</option>@endforeach</x-form.select>
        </x-form.grid></x-form.section>

        <x-form.section title="Material Inputs">
            <div class="overflow-x-auto"><table class="min-w-[66rem] w-full text-xs"><thead><tr>@foreach (['#', 'Material', 'Formula Qty', 'Type', 'UOM', 'Source Warehouse', 'Notes', ''] as $heading)<th>{{ $heading }}</th>@endforeach</tr></thead><tbody><template x-for="(row, index) in rows" :key="row.key"><tr>
                <td x-text="index + 1"></td>
                <td><div class="relative min-w-64"><input type="hidden" :name="`materials[${index}][item_id]`" x-model="row.item_id"><input type="search" class="w-full" x-model="row.item_text" @input.debounce.250ms="searchMaterial(row, $event)" @focus="searchMaterial(row, $event)" @keydown.escape="row.open=false" @keydown.arrow-down.prevent="moveMaterial(row,1)" @keydown.arrow-up.prevent="moveMaterial(row,-1)" @keydown.enter.prevent="selectActiveMaterial(row)" placeholder="Search SKU or item name..." autocomplete="off" required><div x-show="row.open" x-cloak @click.outside="row.open=false" :style="row.dropdownStyle" class="theme-dropdown fixed z-[9999] max-h-60 overflow-y-auto rounded-lg shadow-xl" role="listbox"><div x-show="row.loading" class="px-3 py-2">Loading...</div><template x-for="(option, optionIndex) in row.results" :key="option.id"><button type="button" class="theme-option block w-full px-3 py-2 text-left" :class="row.activeIndex === optionIndex ? 'theme-primary-soft' : ''" @click="selectMaterial(row, option)"><span class="block font-semibold" x-text="option.text"></span><span class="block text-xs theme-muted" x-text="option.meta_text"></span></button></template><div x-show="!row.loading && row.item_text.length >= 2 && !row.results.length" class="px-3 py-2 theme-muted">No eligible materials found.</div></div></div></td>
                <td><input :name="`materials[${index}][quantity]`" x-model="row.quantity" type="number" min="0.000001" step="0.000001" class="w-28 text-right" required></td>
                <td><select :name="`materials[${index}][quantity_type]`" x-model="row.quantity_type"><option value="proportional">Proportional</option><option value="fixed">Fixed</option></select></td>
                <td><input type="hidden" :name="`materials[${index}][uom_id]`" x-model="row.uom_id"><span class="inline-flex rounded-md px-2 py-1 text-xs font-bold theme-primary-soft" x-text="row.uom_code || '-'"></span></td>
                <td class="min-w-[17rem]"><select :name="`materials[${index}][source_warehouse_id]`" x-model="row.source_warehouse_id" class="w-72"><option value="" x-text="defaultSourceLabel()"></option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" data-company="{{ $warehouse->company_id ?: $warehouse->branch?->company_id }}" data-branch="{{ $warehouse->branch_id }}" data-type="{{ $warehouse->warehouseType?->code }}">{{ $warehouseLabel($warehouse) }}</option>@endforeach</select></td>
                <td><input :name="`materials[${index}][notes]`" x-model="row.notes" class="w-40"></td><td><button type="button" class="text-red-600 font-bold" @click="rows.splice(index,1)" :disabled="rows.length===1" aria-label="Remove material">Remove</button></td>
            </tr></template></tbody></table></div>
            <button type="button" class="button-primary mt-3" @click="addRow">Add Material</button>
        </x-form.section>

        <x-form.section title="Requirement Preview"><div class="theme-surface-secondary rounded-lg p-3"><div class="mb-3 flex flex-wrap items-end gap-4"><div><span class="block text-xs font-bold theme-muted">Base Formula Output</span><span class="font-black" x-text="format(baseOutput)+' '+(outputCode || '')"></span></div><div class="w-48"><label class="enterprise-form-label">Preview Production Qty</label><div class="flex items-center gap-2"><input name="preview_only" type="number" min="0.000001" step="0.000001" class="w-full text-right" x-model="preview" @input="previewTouched=true"><span class="font-bold" x-text="outputCode || '-' "></span></div></div></div><div class="overflow-x-auto"><table class="min-w-[60rem] w-full text-sm"><thead><tr><th>Material</th><th>Quantity Type</th><th class="text-right">Formula Qty</th><th class="text-right">Required Qty</th><th>UOM</th><th>Effective Source</th></tr></thead><tbody><template x-for="row in rows" :key="row.key"><tr><td x-text="row.item_text || 'Select material'"></td><td class="capitalize" x-text="row.quantity_type"></td><td class="text-right tabular-nums" x-text="format(row.quantity)"></td><td class="text-right font-black tabular-nums" x-text="requirement(row)"></td><td x-text="row.uom_code || '-' "></td><td class="min-w-64" x-text="effectiveSource(row)"></td></tr></template><tr x-show="!rows.length"><td colspan="6" class="py-3 text-center theme-muted">Add a material to preview requirements.</td></tr></tbody></table></div></div></x-form.section>
        <x-form.action-bar :sticky="false"><a class="filter-button-secondary" href="{{ route('production-formulas.index') }}">Cancel</a><button class="button-primary">Save Draft</button></x-form.action-bar>
    </form>

    <script>
        function formulaForm(initial, itemUrl) { return {
            rows: initial.map((row, index) => ({...row, key: Date.now()+index, results: [], open: false, loading: false, activeIndex: -1, dropdownStyle: 'display:none'})), itemUrl,
            productionType: @js(old('production_type', $formula->production_type ?: 'STANDARD')), formulaName: @js(old('name', $formula->name ?: '')), nameTouched: Boolean(@js(old('name', $formula->name ?: ''))),
            finishedItem: @js((string) $selectedFinishedId), finishedName: @js($selectedFinished?->name ?? ''), outputUom: @js((string) old('output_uom_id', $formula->output_uom_id)), outputCode: @js($formula->outputUom?->code ?? $selectedFinished?->baseUnit?->code ?? ''),
            baseOutput: @js((string) old('base_output_quantity', $formula->base_output_quantity ?: 1)), preview: @js((string) old('base_output_quantity', $formula->base_output_quantity ?: 1)), previewTouched: false, defaultSourceWarehouseId: @js((string) old('default_source_warehouse_id', $formula->default_source_warehouse_id)),
            init() { this.$nextTick(() => { this.refreshBranches(); this.refreshWarehouses(); }); this.$root.querySelector('[name=company_id]')?.addEventListener('change', () => { this.refreshBranches(); this.refreshWarehouses(true); }); this.$root.querySelector('[name=branch_id]')?.addEventListener('change', () => this.refreshWarehouses(true)); },
            selectFinished(option) { this.finishedItem=String(option.id||''); this.finishedName=String(option.text||'').replace(/^\S+\s+-\s+/, ''); this.outputUom=option.unit_id||''; this.outputCode=option.unit_text||''; this.rows.forEach(row => { if (String(row.item_id) === this.finishedItem) { row.item_id=''; row.item_text=''; row.uom_id=''; row.uom_code=''; } }); this.suggestName(); },
            suggestName() { if (!this.nameTouched && this.finishedName) this.formulaName=`${this.finishedName} ${this.productionType === 'REPACKING' ? 'Repacking' : 'Standard'}`; }, onTypeChanged() { this.suggestName(); this.refreshWarehouses(); },
            addRow() { this.rows.push({key:Date.now(), item_id:'', item_text:'', quantity:'', uom_id:'', uom_code:'', quantity_type:'proportional', source_warehouse_id:'', notes:'', results:[], open:false, loading:false, activeIndex:-1, dropdownStyle:'display:none'}); },
            positionMaterial(row, event) { let rect=event.target.getBoundingClientRect(), below=window.innerHeight-rect.bottom; row.dropdownStyle=`top:${below >= 112 ? rect.bottom+4 : Math.max(12,rect.top-244)}px;left:${rect.left}px;width:${rect.width}px;`; },
            async searchMaterial(row, event) { this.positionMaterial(row,event); row.item_id=''; row.uom_id=''; row.uom_code=''; row.activeIndex=-1; if (row.item_text.trim().length < 2) { row.results=[]; row.open=false; return; } row.loading=true; row.open=true; let url=new URL(this.itemUrl, window.location.origin); url.searchParams.set('q', row.item_text); url.searchParams.set('intent','material'); url.searchParams.set('production_type',this.productionType); try { let response=await fetch(url,{headers:{Accept:'application/json'}}); row.results=response.ok ? await response.json() : []; row.results=row.results.filter(option => String(option.id)!==this.finishedItem); } finally { row.loading=false; } },
            selectMaterial(row, option) { row.item_id=String(option.id); row.item_text=option.text; row.uom_id=String(option.unit_id||''); row.uom_code=option.unit_text||''; row.results=[]; row.open=false; }, moveMaterial(row, step) { if (!row.open || !row.results.length) return; row.activeIndex=(row.activeIndex+step+row.results.length)%row.results.length; }, selectActiveMaterial(row) { if (row.activeIndex >= 0 && row.results[row.activeIndex]) this.selectMaterial(row,row.results[row.activeIndex]); },
            refreshBranches() { let company=this.$root.querySelector('[name=company_id]')?.value||'', select=this.$root.querySelector('[name=branch_id]'); if (!select) return; [...select.options].forEach(option => { if (!option.value) return; let visible=!company || option.dataset.company===company; option.hidden=!visible; option.disabled=!visible; }); if (select.value && select.selectedOptions[0]?.disabled) select.value=''; },
            refreshWarehouses(clear=false) { let company=this.$root.querySelector('[name=company_id]')?.value||'', branch=this.$root.querySelector('[name=branch_id]')?.value||''; this.$root.querySelectorAll('[data-source],[data-destination],select[name*="source_warehouse_id"]').forEach(select => { let valid=[]; [...select.options].forEach(option => { if (!option.value) return; let visible=(!company || option.dataset.company===company) && (!branch || option.dataset.branch===branch); option.hidden=!visible; option.disabled=!visible; if (visible) valid.push(option); }); if (clear && select.value && select.selectedOptions[0]?.disabled) select.value=''; if (branch && !select.value) { let preferred=select.hasAttribute('data-destination') ? ['FINISHED_GOODS','PRODUCTION'] : (this.productionType==='STANDARD' ? ['RAW_MATERIAL','PRODUCTION'] : ['FINISHED_GOODS']); let option=valid.find(candidate => preferred.includes(candidate.dataset.type)); if (option) select.value=option.value; } }); },
            defaultSourceLabel() { let source=this.$root.querySelector('[name=default_source_warehouse_id]'); return source?.selectedOptions[0]?.value ? `Use Formula Default Source - ${source.selectedOptions[0].text}` : 'Use Formula Default Source - Not Set'; },
            warehouseLabel(id) { if (!id) return ''; let option=this.$root.querySelector(`option[value="${id}"][data-company]`); return option?.textContent?.trim() || 'Not selected'; },
            effectiveSource(row) { return this.warehouseLabel(row.source_warehouse_id) || this.warehouseLabel(this.defaultSourceWarehouseId) || 'Not selected'; },
            format(value) { let number=Number(value||0); if (!Number.isFinite(number)) return '0'; return Number(number.toFixed(6)).toString(); }, requirement(row) { let quantity=Number(row.quantity||0), preview=Number(this.preview||0), base=Number(this.baseOutput||0); return this.format(row.quantity_type==='fixed' ? quantity : (base>0 ? quantity*preview/base : 0)); }
        }; }
    </script>
</x-app-layout>
