@php
    use App\Support\QuantityFormatter;
    $warehouseLabel = fn ($warehouse) => $warehouse ? trim($warehouse->code.' - '.$warehouse->name.($warehouse->branch ? ' · '.$warehouse->branch->name : '')) : 'Not selected';
    $today = now()->startOfDay();
    $effectiveState = $formula->effective_from?->gt($today) ? 'Future' : ($formula->effective_to?->lt($today) ? 'Expired' : 'Current');
@endphp
<x-app-layout>
    <x-slot name="header"><x-ui.page-header title="Production Formula" :subtitle="$formula->number"><x-slot:action><div class="flex flex-wrap gap-2"><a class="filter-button-secondary" href="{{ route('production-formulas.index') }}">Back to Formulas</a>@if($formula->status==='draft')<a class="filter-button-secondary" href="{{ route('production-formulas.edit',$formula) }}">Edit</a><form method="POST" action="{{ route('production-formulas.activate',$formula) }}">@csrf<button class="button-primary">Activate</button></form>@endif @if($formula->status==='active')<form method="POST" action="{{ route('production-formulas.inactivate',$formula) }}">@csrf<button class="filter-button-secondary">Inactivate</button></form>@endif @if($formula->status==='inactive')<form method="POST" action="{{ route('production-formulas.obsolete',$formula) }}">@csrf<button class="filter-button-secondary">Mark Obsolete</button></form>@endif<form method="POST" action="{{ route('production-formulas.clone',$formula) }}">@csrf<button class="filter-button-secondary">Clone Formula</button></form></div></x-slot:action></x-ui.page-header></x-slot>
    <div class="enterprise-detail mx-auto max-w-screen-xl space-y-3">@if(session('status'))<div class="status-success rounded-lg px-4 py-3 text-sm font-bold">{{ session('status') }}</div>@endif
        <section class="theme-card rounded-lg p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-[10px] font-black uppercase tracking-widest theme-muted">Production Formula</p><h2 class="mt-1 text-xl font-black">{{ $formula->number }} · {{ $formula->name }}</h2><p class="theme-muted">{{ $formula->finishedItem?->sku }} - {{ $formula->finishedItem?->name }} · Version {{ $formula->version }}</p></div><div class="flex gap-2"><x-ui.status-badge :status="$formula->status" /><span class="rounded-full px-2 py-1 text-xs font-bold theme-primary-soft">{{ $effectiveState }}</span></div></div><dl class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><dt>Type</dt><dd>{{ $formula->production_type }}</dd></div><div><dt>Company / Branch</dt><dd>{{ $formula->company?->name }} / {{ $formula->branch?->name ?: 'Company-wide' }}</dd></div><div><dt>Base Output</dt><dd>{{ QuantityFormatter::display($formula->base_output_quantity) }} {{ $formula->outputUom?->code }}</dd></div><div><dt>Effective Period</dt><dd>{{ $formula->effective_from?->format('d M Y') ?: 'Open' }} - {{ $formula->effective_to?->format('d M Y') ?: 'Open' }}</dd></div><div><dt>Default Source</dt><dd>{{ $warehouseLabel($formula->defaultSourceWarehouse) }}</dd></div><div><dt>Default Destination</dt><dd>{{ $warehouseLabel($formula->defaultDestinationWarehouse) }}</dd></div><div><dt>Activated</dt><dd>@if($formula->activated_at){{ $formula->activated_at->format('d M Y H:i') }}<br><span class="theme-muted">by {{ $formula->activatedBy?->name }}</span>@else—@endif</dd></div><div><dt>Notes</dt><dd>{{ $formula->notes ?: '—' }}</dd></div></dl></section>
        <x-form.section title="Material Inputs"><div class="overflow-x-auto"><table class="w-full min-w-[56rem] text-xs"><thead><tr>@foreach(['#','Material','Quantity','Type','UOM','Effective Source Warehouse','Notes'] as $heading)<th class="px-3 py-2 text-left">{{ $heading }}</th>@endforeach</tr></thead><tbody>@foreach($formula->materials as $material)<tr class="border-t"><td class="px-3 py-2">{{ $material->sequence }}</td><td class="px-3 py-2 font-bold">{{ $material->item?->sku }} - {{ $material->item?->name }}</td><td class="px-3 py-2 text-right">{{ QuantityFormatter::display($material->quantity) }}</td><td class="px-3 py-2">{{ ucfirst($material->quantity_type) }}</td><td class="px-3 py-2">{{ $material->uom?->code }}</td><td class="px-3 py-2">{{ $warehouseLabel($material->sourceWarehouse ?: $formula->defaultSourceWarehouse) }}</td><td class="px-3 py-2">{{ $material->notes ?: '—' }}</td></tr>@endforeach</tbody></table></div></x-form.section>
        <x-form.section title="Requirement Preview"><div x-data="{preview:{{ (float)$formula->base_output_quantity }}, format(value){return Number(Number(value||0).toFixed(6)).toString()}"><div class="mb-3 flex items-end gap-3"><div><span class="block text-xs font-bold theme-muted">Base Formula Output</span><span class="font-black">{{ QuantityFormatter::display($formula->base_output_quantity) }} {{ $formula->outputUom?->code }}</span></div><div><label class="enterprise-form-label">Preview output quantity</label><input class="enterprise-form-control w-48" x-model.number="preview" type="number" min="0.000001" step="0.000001"></div></div><div class="overflow-x-auto"><table class="w-full min-w-[52rem] text-sm"><thead><tr><th>Material</th><th class="text-right">Required Qty</th><th>Type</th><th>Effective Source</th></tr></thead><tbody>@foreach($formula->materials as $material)<tr><td>{{ $material->item?->sku }} - {{ $material->item?->name }}</td><td class="text-right font-black" x-text="format({{ $material->quantity_type==='fixed' ? (float)$material->quantity : '('.(float)$material->quantity.'*preview/'.(float)$formula->base_output_quantity.')' }})+' {{ $material->uom?->code }}'"></td><td>{{ ucfirst($material->quantity_type) }}</td><td>{{ $warehouseLabel($material->sourceWarehouse ?: $formula->defaultSourceWarehouse) }}</td></tr>@endforeach</tbody></table></div></x-form.section>
    </div>
</x-app-layout>
