<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Http\Requests\ProductionBomRequest; use App\Models\{Branch,Company,Item,ProductionBom,User,Warehouse}; use App\Services\Production\ProductionBomService; use Illuminate\Database\Eloquent\Builder; use Illuminate\Http\{JsonResponse,RedirectResponse,Request}; use Illuminate\View\View;
class ProductionBomController extends Controller { public function __construct(private ProductionBomService $service){}
 public function index(Request$r):View{$this->allow($r->user(),'production.bom.view');$f=$r->only(['keyword','company_id','branch_id','production_type','finished_item_id','status','effective_date']);$q=ProductionBom::accessibleTo($r->user())->with(['company','branch','finishedItem.baseUnit'])->when(filled($f['keyword']??null),fn($q)=>$q->where(fn($x)=>$x->where('number','like','%'.$f['keyword'].'%')->orWhere('name','like','%'.$f['keyword'].'%')))->when(filled($f['company_id']??null),fn($q)=>$q->where('company_id',$f['company_id']))->when(filled($f['branch_id']??null),fn($q)=>$q->where('branch_id',$f['branch_id']))->when(filled($f['production_type']??null),fn($q)=>$q->where('production_type',$f['production_type']))->when(filled($f['finished_item_id']??null),fn($q)=>$q->where('finished_item_id',$f['finished_item_id']))->when(filled($f['status']??null),fn($q)=>$q->where('status',$f['status']))->when(filled($f['effective_date']??null),fn($q)=>$q->effectiveOn($f['effective_date']));return view('production.formulas.index',['records'=>$q->latest('id')->paginate(15)->withQueryString(),'filters'=>$f]+$this->options($r->user()));}
 public function create(Request$r):View{$this->allow($r->user(),'production.bom.create');return view('production.formulas.form',['formula'=>new ProductionBom,'materials'=>old('materials',[[]])]+$this->options($r->user()));}
 public function store(ProductionBomRequest$r):RedirectResponse{$this->allow($r->user(),'production.bom.create');$b=$this->service->create($r->validated(),$r->user());return redirect()->route('production-formulas.show',$b)->with('status','Production Formula created.');}
 public function show(Request$r,ProductionBom$formula):View{$this->owned($r->user(),$formula);return view('production.formulas.show',['formula'=>$formula->load(['company','branch','finishedItem.baseUnit','outputUom','defaultSourceWarehouse','defaultDestinationWarehouse','materials.item.baseUnit','materials.uom','materials.sourceWarehouse','outputs.item','activatedBy','inactivatedBy'])]);}
 public function edit(Request$r,ProductionBom$formula):View{$this->owned($r->user(),$formula,'production.bom.edit');abort_unless($formula->status===ProductionBom::STATUS_DRAFT,409);return view('production.formulas.form',['formula'=>$formula->load('materials.item.baseUnit'),'materials'=>old('materials',$formula->materials->toArray())]+$this->options($r->user()));}
 public function update(ProductionBomRequest$r,ProductionBom$formula):RedirectResponse{$this->owned($r->user(),$formula,'production.bom.edit');$this->service->update($formula,$r->validated(),$r->user());return redirect()->route('production-formulas.show',$formula)->with('status','Production Formula updated.');}
 public function activate(Request$r,ProductionBom$formula):RedirectResponse{$this->owned($r->user(),$formula,'production.bom.activate');$this->service->activate($formula,$r->user());return back()->with('status','Formula activated.');} public function inactivate(Request$r,ProductionBom$formula):RedirectResponse{$this->owned($r->user(),$formula,'production.bom.inactivate');$this->service->inactivate($formula,$r->user());return back()->with('status','Formula inactivated.');} public function obsolete(Request$r,ProductionBom$formula):RedirectResponse{$this->owned($r->user(),$formula,'production.bom.obsolete');$this->service->obsolete($formula,$r->user());return back()->with('status','Formula marked obsolete.');}
 public function clone(Request$r,ProductionBom$formula):RedirectResponse{$this->owned($r->user(),$formula,'production.bom.clone');$copy=$this->service->clone($formula,$r->user());return redirect()->route('production-formulas.edit',$copy)->with('status','Cloned from '.$formula->number.'.');}
 public function items(Request$r):JsonResponse{$this->allow($r->user(),'production.bom.view');$term=trim((string)$r->query('q'));if(mb_strlen($term)<2)return response()->json([]);$intent=$r->query('intent')==='output'?'output':'material';$type=in_array($r->query('production_type'),ProductionBom::TYPES,true)?$r->query('production_type'):ProductionBom::TYPE_STANDARD;$eligibility=app(\App\Services\Production\ProductionItemEligibility::class);$query=$intent==='output'?$eligibility->outputQuery():$eligibility->materialQuery($type);return response()->json($query->where(fn(Builder$q)=>$q->where('sku','like','%'.$term.'%')->orWhere('name','like','%'.$term.'%'))->with(['baseUnit','category'])->orderByRaw('CASE WHEN LOWER(sku) = ? THEN 0 WHEN LOWER(sku) LIKE ? THEN 1 ELSE 2 END',[strtolower($term),strtolower($term).'%'])->orderBy('sku')->limit(20)->get()->map(fn(Item$i)=>['id'=>$i->id,'text'=>trim($i->sku.' — '.$i->name),'unit_id'=>$i->base_unit_id,'unit_text'=>$i->baseUnit?->code,'meta_text'=>trim(($i->category?->name?:'Inventory').' · '.($i->baseUnit?->code?:'-'))]));}
 private function options(User$u):array{$branches=Branch::query()->where('is_active',true)->when(!$u->isSuperAdmin(),fn($q)=>$q->whereHas('users',fn($x)=>$x->whereKey($u->id)))->orderBy('name')->get();$companies=Company::query()->where('is_active',true)->whereIn('id',$branches->pluck('company_id'))->orderBy('name')->pluck('name','id');$warehouses=Warehouse::query()->with(['branch','warehouseType'])->where('is_active',true)->whereIn('branch_id',$branches->pluck('id'))->get()->sortBy(fn(Warehouse$w)=>sprintf('%s|%s|%s',$w->branch?->name??'', $w->warehouseType?->code??'', $w->code));$eligibility=app(\App\Services\Production\ProductionItemEligibility::class);$items=$eligibility->materialQuery(ProductionBom::TYPE_REPACKING)->with(['baseUnit','category'])->orderBy('sku')->limit(500)->get();$defaultCompanyId=$companies->count()===1?(int)$companies->keys()->first():null;$companyBranches=$defaultCompanyId?$branches->where('company_id',$defaultCompanyId):collect();$defaultBranchId=$companyBranches->count()===1?(int)$companyBranches->first()->id:null;return compact('branches','companies','warehouses','items','defaultCompanyId','defaultBranchId');}
 private function allow(User$u,string$p):void{abort_unless($u->canPerform($p,'production'),403);} private function owned(User$u,ProductionBom$b,string$p='production.bom.view'):void{$this->allow($u,$p);abort_unless(ProductionBom::accessibleTo($u)->whereKey($b->getKey())->exists(),403);}
}
